const priceRangeOptions = [
  { value: "", label: "Any Price" },
  { value: "0-50", label: "$0 - $50" },
  { value: "51-100", label: "$51 - $100" },
  { value: "101-200", label: "$101 - $200" },
  { value: "201-500", label: "$201 - $500" },
  { value: "500+", label: "$500+" },
];

const statusOptions = [
  { value: "", label: "All Status" },
  { value: "active", label: "Active" },
  { value: "draft", label: "Draft" },
  { value: "archived", label: "Archived" },
  { value: "full", label: "Full" },
];

const trialOptions = [
  { value: "", label: "All Courses" },
  { value: "yes", label: "Trial Available" },
  { value: "no", label: "No Trial" },
];

const mockCourses = [
  {
    id: "1",
    courseName: "Business English Fundamentals",
    description:
      "Master essential business communication skills for professional success in English-speaking environments.",
    category: "Business English",
    language: "en",
    targetAudience: "Intermediate",
    price: 299,
    trialAvailable: true,
    capacity: 20,
    studentCount: 15,
    duration: "8 weeks",
    startDate: "2024-09-01",
    endDate: "2024-10-26",
    teacher: "Sarah Johnson",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-01",
    lessonType: "group",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 18, max: 45 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Interactive Practice Session",
        lessonDescription:
          "Detailed description for Interactive Practice Session.",
        trialAvailable: true,
        trialCapacity: 5,
        curriculumGames: false,
      },
      {
        lessonTitle: "Midterm Review",
        lessonDescription: "Detailed description for Midterm Review.",
        trialAvailable: false,
        trialCapacity: 3,
        curriculumGames: true,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "2",
    courseName: "Conversational Spanish for Beginners",
    description:
      "Learn to speak Spanish confidently in everyday situations with interactive lessons and practical exercises.",
    category: "Conversational",
    language: "es",
    targetAudience: "Beginner",
    price: 199,
    trialAvailable: true,
    capacity: 15,
    studentCount: 12,
    duration: "10 weeks",
    startDate: "2024-09-15",
    endDate: "2024-11-23",
    teacher: "Michael Chen",
    status: "active",
    lessonCount: 20,
    createdAt: "2024-08-05",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 16, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "3",
    courseName: "IELTS Preparation Intensive",
    description:
      "Comprehensive IELTS exam preparation covering all four skills: listening, reading, writing, and speaking.",
    category: "Exam Preparation",
    language: "en",
    targetAudience: "Advanced",
    price: 449,
    trialAvailable: false,
    capacity: 12,
    studentCount: 12,
    duration: "12 weeks",
    startDate: "2024-08-20",
    endDate: "2024-11-12",
    teacher: "Emma Rodriguez",
    status: "full",
    lessonCount: 24,
    createdAt: "2024-07-15",
    lessonType: "1-on-1",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 18, max: 40 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "4",
    courseName: "French for Kids (Ages 8-12)",
    description:
      "Fun and engaging French lessons designed specifically for children with games, songs, and interactive activities.",
    category: "Kids & Teens",
    language: "fr",
    targetAudience: "Beginner",
    price: 149,
    trialAvailable: true,
    capacity: 10,
    studentCount: 8,
    duration: "6 weeks",
    startDate: "2024-09-10",
    endDate: "2024-10-21",
    teacher: "David Kim",
    status: "active",
    lessonCount: 12,
    createdAt: "2024-08-10",
    lessonType: "group",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 8, max: 12 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "5",
    courseName: "German Grammar Mastery",
    description:
      "Deep dive into German grammar structures with comprehensive exercises and real-world applications.",
    category: "Academic",
    language: "de",
    targetAudience: "Intermediate",
    price: 0,
    trialAvailable: false,
    capacity: 25,
    studentCount: 18,
    duration: "14 weeks",
    startDate: "2024-08-15",
    endDate: "2024-11-21",
    teacher: "Lisa Anderson",
    status: "archived",
    lessonCount: 28,
    createdAt: "2024-07-20",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 20, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "6",
    courseName: "Professional Italian Communication",
    description:
      "Advanced Italian course focused on professional communication, presentations, and business correspondence.",
    category: "Professional",
    language: "it",
    targetAudience: "Advanced",
    price: 399,
    trialAvailable: true,
    capacity: 15,
    studentCount: 5,
    duration: "10 weeks",
    startDate: "2024-10-01",
    endDate: "2024-12-10",
    teacher: "Sarah Johnson",
    status: "draft",
    lessonCount: 20,
    createdAt: "2024-08-12",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 22, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "7",
    courseName: "Mandarin Chinese Basics",
    description:
      "Learn basic Mandarin vocabulary, tones, and conversational skills for everyday situations.",
    category: "Conversational",
    language: "zh",
    targetAudience: "Beginner",
    price: 249,
    trialAvailable: true,
    capacity: 18,
    studentCount: 10,
    duration: "8 weeks",
    startDate: "2024-09-20",
    endDate: "2024-11-15",
    teacher: "Wei Zhang",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-15",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 15, max: 45 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "8",
    courseName: "TOEFL Success Program",
    description:
      "Focused preparation for the TOEFL exam with strategies, mock tests, and practice exercises.",
    category: "Exam Preparation",
    language: "en",
    targetAudience: "Intermediate",
    price: 399,
    trialAvailable: false,
    capacity: 20,
    studentCount: 19,
    duration: "10 weeks",
    startDate: "2024-08-25",
    endDate: "2024-11-02",
    teacher: "John Miller",
    status: "full",
    lessonCount: 20,
    createdAt: "2024-07-25",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 18, max: 40 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "9",
    courseName: "Japanese Conversation for Travelers",
    description:
      "Essential Japanese phrases and cultural tips to navigate travel and daily life in Japan.",
    category: "Travel",
    language: "ja",
    targetAudience: "Beginner",
    price: 129,
    trialAvailable: true,
    capacity: 12,
    studentCount: 7,
    duration: "4 weeks",
    startDate: "2024-10-05",
    endDate: "2024-11-02",
    teacher: "Yuki Tanaka",
    status: "active",
    lessonCount: 8,
    createdAt: "2024-09-01",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 18, max: 55 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "10",
    courseName: "Portuguese for Business",
    description:
      "Learn professional Portuguese communication skills for working with Brazilian and European partners.",
    category: "Business",
    language: "pt",
    targetAudience: "Intermediate",
    price: 299,
    trialAvailable: true,
    capacity: 20,
    studentCount: 14,
    duration: "8 weeks",
    startDate: "2024-09-28",
    endDate: "2024-11-23",
    teacher: "Ana Silva",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-18",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 20, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "11",
    courseName: "Advanced Grammar for English Teachers",
    description:
      "In-depth grammar training designed for English teachers to improve classroom instruction.",
    category: "Academic",
    language: "en",
    targetAudience: "Advanced",
    price: 299,
    trialAvailable: false,
    capacity: 20,
    studentCount: 20,
    duration: "10 weeks",
    startDate: "2024-08-18",
    endDate: "2024-10-27",
    teacher: "Mark Thompson",
    status: "full",
    lessonCount: 20,
    createdAt: "2024-07-30",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 25, max: 55 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "12",
    courseName: "Creative Writing in English",
    description:
      "Develop storytelling, narrative, and creative writing skills in English with guided exercises.",
    category: "Creative",
    language: "en",
    targetAudience: "Intermediate",
    price: 199,
    trialAvailable: true,
    capacity: 15,
    studentCount: 11,
    duration: "8 weeks",
    startDate: "2024-09-12",
    endDate: "2024-11-07",
    teacher: "Rachel Lee",
    status: "archived",
    lessonCount: 16,
    createdAt: "2024-08-08",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 16, max: 45 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "13",
    courseName: "Public Speaking in English",
    description:
      "Build confidence and skills for public speaking, presentations, and debates in English.",
    category: "Professional",
    language: "en",
    targetAudience: "Intermediate",
    price: 249,
    trialAvailable: true,
    capacity: 15,
    studentCount: 13,
    duration: "8 weeks",
    startDate: "2024-09-02",
    endDate: "2024-10-28",
    teacher: "Emily Carter",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-03",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 18, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "14",
    courseName: "Korean Drama Language Lab",
    description:
      "Learn conversational Korean through popular K-dramas, dialogues, and cultural exploration.",
    category: "Conversational",
    language: "ko",
    targetAudience: "Intermediate",
    price: 179,
    trialAvailable: true,
    capacity: 18,
    studentCount: 9,
    duration: "6 weeks",
    startDate: "2024-09-25",
    endDate: "2024-11-06",
    teacher: "Jinwoo Park",
    status: "draft",
    lessonCount: 12,
    createdAt: "2024-08-22",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 16, max: 40 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "15",
    courseName: "Portuguese Conversation Basics",
    description:
      "Practice everyday Portuguese with dialogues, role-play, and cultural notes.",
    category: "Conversational",
    language: "pt",
    targetAudience: "Beginner",
    price: 159,
    trialAvailable: true,
    capacity: 15,
    studentCount: 12,
    duration: "6 weeks",
    startDate: "2024-09-29",
    endDate: "2024-11-09",
    teacher: "Carlos Mendes",
    status: "active",
    lessonCount: 12,
    createdAt: "2024-08-20",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 15, max: 45 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "16",
    courseName: "Business German Essentials",
    description:
      "Professional German for business meetings, negotiations, and workplace communication.",
    category: "Business",
    language: "de",
    targetAudience: "Intermediate",
    price: 349,
    trialAvailable: true,
    capacity: 12,
    studentCount: 6,
    duration: "8 weeks",
    startDate: "2024-10-05",
    endDate: "2024-11-30",
    teacher: "Hans Müller",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-22",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 20, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "17",
    courseName: "Advanced Italian Literature",
    description:
      "Study Italian literature with advanced reading and analysis exercises.",
    category: "Academic",
    language: "it",
    targetAudience: "Advanced",
    price: 399,
    trialAvailable: false,
    capacity: 10,
    studentCount: 9,
    duration: "12 weeks",
    startDate: "2024-09-17",
    endDate: "2024-12-10",
    teacher: "Giovanni Rossi",
    status: "archived",
    lessonCount: 24,
    createdAt: "2024-08-14",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 22, max: 55 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "18",
    courseName: "Beginner Japanese Kanji",
    description:
      "Learn essential kanji characters for reading and writing Japanese.",
    category: "Academic",
    language: "ja",
    targetAudience: "Beginner",
    price: 199,
    trialAvailable: true,
    capacity: 20,
    studentCount: 16,
    duration: "8 weeks",
    startDate: "2024-10-02",
    endDate: "2024-11-27",
    teacher: "Haruto Sato",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-28",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 15, max: 45 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "19",
    courseName: "Chinese for Professionals",
    description:
      "Business Mandarin course covering negotiation, email, and presentation language.",
    category: "Business",
    language: "zh",
    targetAudience: "Advanced",
    price: 499,
    trialAvailable: false,
    capacity: 15,
    studentCount: 14,
    duration: "10 weeks",
    startDate: "2024-09-21",
    endDate: "2024-11-30",
    teacher: "Mei Lin",
    status: "draft",
    lessonCount: 20,
    createdAt: "2024-08-25",
    lessonType: "1-on-1",
    lessonMode: "online",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 25, max: 55 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
  {
    id: "20",
    courseName: "Spanish for Healthcare Workers",
    description:
      "Essential Spanish for nurses, doctors, and healthcare professionals.",
    category: "Professional",
    language: "ja",
    targetAudience: "Intermediate",
    price: 299,
    trialAvailable: true,
    capacity: 15,
    studentCount: 13,
    duration: "8 weeks",
    startDate: "2024-10-01",
    endDate: "2024-11-26",
    teacher: "Laura González",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-29",
    lessonType: "group",
    lessonMode: "in-person",
    introImage: "Screenshot from 2025-09-03 15-53-08.png",
    ageRange: { min: 21, max: 50 },
    lessons: [
      {
        lessonTitle: "Introduction to the Course",
        lessonDescription:
          "Detailed description for Introduction to the Course.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: true,
      },
      {
        lessonTitle: "Key Concepts Overview",
        lessonDescription: "Detailed description for Key Concepts Overview.",
        trialAvailable: true,
        trialCapacity: 4,
        curriculumGames: false,
      },
      {
        lessonTitle: "Final Assessment",
        lessonDescription: "Detailed description for Final Assessment.",
        trialAvailable: false,
        trialCapacity: 2,
        curriculumGames: true,
      },
    ],
  },
];

export { priceRangeOptions, statusOptions, trialOptions, mockCourses };
