const languageOptions = [
  { value: "", label: "All Languages" },
  { value: "english", label: "English" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "italian", label: "Italian" },
  { value: "portuguese", label: "Portuguese" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
];

const priceRangeOptions = [
  { value: "", label: "Any Price" },
  { value: "0-50", label: "$0 - $50" },
  { value: "51-100", label: "$51 - $100" },
  { value: "101-200", label: "$101 - $200" },
  { value: "201-500", label: "$201 - $500" },
  { value: "500+", label: "$500+" },
];

const statusOptions = [
  { value: "", label: "All Status" },
  { value: "active", label: "Active" },
  { value: "draft", label: "Draft" },
  { value: "archived", label: "Archived" },
  { value: "full", label: "Full" },
];

const trialOptions = [
  { value: "", label: "All Courses" },
  { value: "yes", label: "Trial Available" },
  { value: "no", label: "No Trial" },
];

const mockCourses = [
  {
    id: "1",
    title: "Business English Fundamentals",
    description:
      "Master essential business communication skills for professional success in English-speaking environments.",
    category: "Business English",
    language: "english",
    targetAudience: "Intermediate",
    price: 299,
    trialAvailable: true,
    maxStudents: 20,
    studentCount: 15,
    duration: "8 weeks",
    startDate: "2024-09-01",
    endDate: "2024-10-26",
    teacher: "Sarah Johnson",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-01",
  },
  {
    id: "2",
    title: "Conversational Spanish for Beginners",
    description:
      "Learn to speak Spanish confidently in everyday situations with interactive lessons and practical exercises.",
    category: "Conversational",
    language: "spanish",
    targetAudience: "Beginner",
    price: 199,
    trialAvailable: true,
    maxStudents: 15,
    studentCount: 12,
    duration: "10 weeks",
    startDate: "2024-09-15",
    endDate: "2024-11-23",
    teacher: "Michael Chen",
    status: "active",
    lessonCount: 20,
    createdAt: "2024-08-05",
  },
  {
    id: "3",
    title: "IELTS Preparation Intensive",
    description:
      "Comprehensive IELTS exam preparation covering all four skills: listening, reading, writing, and speaking.",
    category: "Exam Preparation",
    language: "english",
    targetAudience: "Advanced",
    price: 449,
    trialAvailable: false,
    maxStudents: 12,
    studentCount: 12,
    duration: "12 weeks",
    startDate: "2024-08-20",
    endDate: "2024-11-12",
    teacher: "Emma Rodriguez",
    status: "full",
    lessonCount: 24,
    createdAt: "2024-07-15",
  },
  {
    id: "4",
    title: "French for Kids (Ages 8-12)",
    description:
      "Fun and engaging French lessons designed specifically for children with games, songs, and interactive activities.",
    category: "Kids & Teens",
    language: "french",
    targetAudience: "Beginner",
    price: 149,
    trialAvailable: true,
    maxStudents: 10,
    studentCount: 8,
    duration: "6 weeks",
    startDate: "2024-09-10",
    endDate: "2024-10-21",
    teacher: "David Kim",
    status: "active",
    lessonCount: 12,
    createdAt: "2024-08-10",
  },
  {
    id: "5",
    title: "German Grammar Mastery",
    description:
      "Deep dive into German grammar structures with comprehensive exercises and real-world applications.",
    category: "Academic",
    language: "german",
    targetAudience: "Intermediate",
    price: 0,
    trialAvailable: false,
    maxStudents: 25,
    studentCount: 18,
    duration: "14 weeks",
    startDate: "2024-08-15",
    endDate: "2024-11-21",
    teacher: "Lisa Anderson",
    status: "archived",
    lessonCount: 28,
    createdAt: "2024-07-20",
  },
  {
    id: "6",
    title: "Professional Italian Communication",
    description:
      "Advanced Italian course focused on professional communication, presentations, and business correspondence.",
    category: "Professional",
    language: "italian",
    targetAudience: "Advanced",
    price: 399,
    trialAvailable: true,
    maxStudents: 15,
    studentCount: 5,
    duration: "10 weeks",
    startDate: "2024-10-01",
    endDate: "2024-12-10",
    teacher: "Sarah Johnson",
    status: "draft",
    lessonCount: 20,
    createdAt: "2024-08-12",
  },
  {
    id: "7",
    title: "Mandarin Chinese Basics",
    description:
      "Learn basic Mandarin vocabulary, tones, and conversational skills for everyday situations.",
    category: "Conversational",
    language: "chinese",
    targetAudience: "Beginner",
    price: 249,
    trialAvailable: true,
    maxStudents: 18,
    studentCount: 10,
    duration: "8 weeks",
    startDate: "2024-09-20",
    endDate: "2024-11-15",
    teacher: "Wei Zhang",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-15",
  },
  {
    id: "8",
    title: "TOEFL Success Program",
    description:
      "Focused preparation for the TOEFL exam with strategies, mock tests, and practice exercises.",
    category: "Exam Preparation",
    language: "english",
    targetAudience: "Intermediate",
    price: 399,
    trialAvailable: false,
    maxStudents: 20,
    studentCount: 19,
    duration: "10 weeks",
    startDate: "2024-08-25",
    endDate: "2024-11-02",
    teacher: "John Miller",
    status: "full",
    lessonCount: 20,
    createdAt: "2024-07-25",
  },
  {
    id: "9",
    title: "Japanese Conversation for Travelers",
    description:
      "Essential Japanese phrases and cultural tips to navigate travel and daily life in Japan.",
    category: "Travel",
    language: "japanese",
    targetAudience: "Beginner",
    price: 129,
    trialAvailable: true,
    maxStudents: 12,
    studentCount: 7,
    duration: "4 weeks",
    startDate: "2024-10-05",
    endDate: "2024-11-02",
    teacher: "Yuki Tanaka",
    status: "active",
    lessonCount: 8,
    createdAt: "2024-09-01",
  },
  {
    id: "10",
    title: "Portuguese for Business",
    description:
      "Learn professional Portuguese communication skills for working with Brazilian and European partners.",
    category: "Business",
    language: "portuguese",
    targetAudience: "Intermediate",
    price: 299,
    trialAvailable: true,
    maxStudents: 20,
    studentCount: 14,
    duration: "8 weeks",
    startDate: "2024-09-28",
    endDate: "2024-11-23",
    teacher: "Ana Silva",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-18",
  },
  {
    id: "11",
    title: "Advanced Grammar for English Teachers",
    description:
      "In-depth grammar training designed for English teachers to improve classroom instruction.",
    category: "Academic",
    language: "english",
    targetAudience: "Advanced",
    price: 299,
    trialAvailable: false,
    maxStudents: 20,
    studentCount: 20,
    duration: "10 weeks",
    startDate: "2024-08-18",
    endDate: "2024-10-27",
    teacher: "Mark Thompson",
    status: "full",
    lessonCount: 20,
    createdAt: "2024-07-30",
  },
  {
    id: "12",
    title: "Creative Writing in English",
    description:
      "Develop storytelling, narrative, and creative writing skills in English with guided exercises.",
    category: "Creative",
    language: "english",
    targetAudience: "Intermediate",
    price: 199,
    trialAvailable: true,
    maxStudents: 15,
    studentCount: 11,
    duration: "8 weeks",
    startDate: "2024-09-12",
    endDate: "2024-11-07",
    teacher: "Rachel Lee",
    status: "archived",
    lessonCount: 16,
    createdAt: "2024-08-08",
  },
  {
    id: "13",
    title: "Public Speaking in English",
    description:
      "Build confidence and skills for public speaking, presentations, and debates in English.",
    category: "Professional",
    language: "english",
    targetAudience: "Intermediate",
    price: 249,
    trialAvailable: true,
    maxStudents: 15,
    studentCount: 13,
    duration: "8 weeks",
    startDate: "2024-09-02",
    endDate: "2024-10-28",
    teacher: "Emily Carter",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-03",
  },
  {
    id: "14",
    title: "Korean Drama Language Lab",
    description:
      "Learn conversational Korean through popular K-dramas, dialogues, and cultural exploration.",
    category: "Conversational",
    language: "japanese", // (using japanese since korean not in your options)
    targetAudience: "Intermediate",
    price: 179,
    trialAvailable: true,
    maxStudents: 18,
    studentCount: 9,
    duration: "6 weeks",
    startDate: "2024-09-25",
    endDate: "2024-11-06",
    teacher: "Jinwoo Park",
    status: "draft",
    lessonCount: 12,
    createdAt: "2024-08-22",
  },
  {
    id: "15",
    title: "Portuguese Conversation Basics",
    description:
      "Practice everyday Portuguese with dialogues, role-play, and cultural notes.",
    category: "Conversational",
    language: "portuguese",
    targetAudience: "Beginner",
    price: 159,
    trialAvailable: true,
    maxStudents: 15,
    studentCount: 12,
    duration: "6 weeks",
    startDate: "2024-09-29",
    endDate: "2024-11-09",
    teacher: "Carlos Mendes",
    status: "active",
    lessonCount: 12,
    createdAt: "2024-08-20",
  },
  {
    id: "16",
    title: "Business German Essentials",
    description:
      "Professional German for business meetings, negotiations, and workplace communication.",
    category: "Business",
    language: "german",
    targetAudience: "Intermediate",
    price: 349,
    trialAvailable: true,
    maxStudents: 12,
    studentCount: 6,
    duration: "8 weeks",
    startDate: "2024-10-05",
    endDate: "2024-11-30",
    teacher: "Hans Müller",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-22",
  },
  {
    id: "17",
    title: "Advanced Italian Literature",
    description:
      "Study Italian literature with advanced reading and analysis exercises.",
    category: "Academic",
    language: "italian",
    targetAudience: "Advanced",
    price: 399,
    trialAvailable: false,
    maxStudents: 10,
    studentCount: 9,
    duration: "12 weeks",
    startDate: "2024-09-17",
    endDate: "2024-12-10",
    teacher: "Giovanni Rossi",
    status: "archived",
    lessonCount: 24,
    createdAt: "2024-08-14",
  },
  {
    id: "18",
    title: "Beginner Japanese Kanji",
    description:
      "Learn essential kanji characters for reading and writing Japanese.",
    category: "Academic",
    language: "japanese",
    targetAudience: "Beginner",
    price: 199,
    trialAvailable: true,
    maxStudents: 20,
    studentCount: 16,
    duration: "8 weeks",
    startDate: "2024-10-02",
    endDate: "2024-11-27",
    teacher: "Haruto Sato",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-28",
  },
  {
    id: "19",
    title: "Chinese for Professionals",
    description:
      "Business Mandarin course covering negotiation, email, and presentation language.",
    category: "Business",
    language: "chinese",
    targetAudience: "Advanced",
    price: 499,
    trialAvailable: false,
    maxStudents: 15,
    studentCount: 14,
    duration: "10 weeks",
    startDate: "2024-09-21",
    endDate: "2024-11-30",
    teacher: "Mei Lin",
    status: "draft",
    lessonCount: 20,
    createdAt: "2024-08-25",
  },
  {
    id: "20",
    title: "Spanish for Healthcare Workers",
    description:
      "Essential Spanish for nurses, doctors, and healthcare professionals.",
    category: "Professional",
    language: "spanish",
    targetAudience: "Intermediate",
    price: 299,
    trialAvailable: true,
    maxStudents: 15,
    studentCount: 13,
    duration: "8 weeks",
    startDate: "2024-10-01",
    endDate: "2024-11-26",
    teacher: "Laura González",
    status: "active",
    lessonCount: 16,
    createdAt: "2024-08-29",
  },
];

export {
  languageOptions,
  priceRangeOptions,
  statusOptions,
  trialOptions,
  mockCourses,
};
