// Mock lesson data
const mockLessons = [
  {
    id: 1,
    date: "2025-01-15",
    time: "10:00",
    subject: "Spanish",
    duration: 60,
    status: "pending",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Emma Johnson", age: 12, status: "Trial Lesson" },
      { name: "Liam Smith", age: 14, status: "Enrolled" },
      { name: "Sophia Davis", age: 13, status: "Enrolled" },
      { name: "Olivia Martinez", age: 12, status: "Trial Lesson" },
      { name: "Noah Wilson", age: 15, status: "Enrolled" },
      { name: "James Anderson", age: 13, status: "Enrolled" },
    ],
  },
  {
    id: 2,
    date: "2025-01-20",
    time: "14:30",
    studentName: "Liam Smith",
    studentAge: 14,
    subject: "English Literature",
    duration: 45,
    status: "confirmed",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 3,
    date: "2025-02-02",
    time: "09:00",
    subject: "Japanese Writing",
    duration: 50,
    status: "completed",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Sophia Davis", age: 13, status: "Enrolled" },
      { name: "Benjamin Lee", age: 15, status: "Trial Lesson" },
      { name: "Charlotte Clark", age: 12, status: "Enrolled" },
      { name: "Ava Taylor", age: 14, status: "Enrolled" },
      { name: "Ella Robinson", age: 13, status: "Trial Lesson" },
    ],
  },
  {
    id: 4,
    date: "2025-02-10",
    time: "16:00",
    studentName: "Noah Wilson",
    studentAge: 15,
    subject: "Spanish Conversation",
    duration: 40,
    status: "cancelled",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 5,
    date: "2025-03-05",
    time: "11:15",
    subject: "French",
    duration: 60,
    status: "confirmed",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Olivia Martinez", age: 12, status: "Trial Lesson" },
      { name: "Ethan Brown", age: 16, status: "Enrolled" },
      { name: "Harper King", age: 14, status: "Enrolled" },
      { name: "Isabella Thomas", age: 12, status: "Trial Lesson" },
      { name: "Michael Scott", age: 12, status: "Enrolled" },
      { name: "William Lewis", age: 16, status: "Enrolled" },
      { name: "Amelia Walker", age: 13, status: "Trial Lesson" },
    ],
  },
  {
    id: 6,
    date: "2025-03-18",
    time: "13:00",
    studentName: "Ethan Brown",
    studentAge: 16,
    subject: "English Grammar",
    duration: 55,
    status: "pending",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 7,
    date: "2025-04-07",
    time: "15:30",
    subject: "Spanish Reading",
    duration: 45,
    status: "completed",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Ava Taylor", age: 14, status: "Enrolled" },
      { name: "Benjamin Lee", age: 15, status: "Trial Lesson" },
      { name: "Mia White", age: 13, status: "Enrolled" },
      { name: "Sophia Davis", age: 13, status: "Trial Lesson" },
      { name: "Emma Johnson", age: 12, status: "Enrolled" },
    ],
  },
  {
    id: 8,
    date: "2025-04-15",
    time: "17:00",
    studentName: "James Anderson",
    studentAge: 13,
    subject: "German",
    duration: 60,
    status: "confirmed",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 9,
    date: "2025-05-01",
    time: "10:30",
    studentName: "Isabella Thomas",
    studentAge: 12,
    subject: "Spanish",
    duration: 40,
    status: "pending",
    type: "online",
    courseType: "1-on-1",
  },
  {
    id: 10,
    date: "2025-05-12",
    time: "09:45",
    subject: "Japanese Conversation",
    duration: 50,
    status: "cancelled",
    type: "in-person",
    courseType: "Group",
    students: [
      { name: "Benjamin Lee", age: 15, status: "Enrolled" },
      { name: "Daniel Young", age: 15, status: "Trial Lesson" },
      { name: "James Anderson", age: 13, status: "Enrolled" },
      { name: "Charlotte Clark", age: 12, status: "Enrolled" },
      { name: "Amelia Walker", age: 13, status: "Trial Lesson" },
      { name: "Harper King", age: 14, status: "Enrolled" },
    ],
  },
  {
    id: 11,
    date: "2025-06-08",
    time: "12:00",
    subject: "French",
    duration: 60,
    status: "completed",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Mia White", age: 13, status: "Enrolled" },
      { name: "Olivia Martinez", age: 12, status: "Trial Lesson" },
      { name: "Emma Johnson", age: 12, status: "Enrolled" },
      { name: "Isabella Thomas", age: 12, status: "Enrolled" },
      { name: "William Lewis", age: 16, status: "Trial Lesson" },
      { name: "James Anderson", age: 13, status: "Enrolled" },
    ],
  },
  {
    id: 12,
    date: "2025-06-20",
    time: "14:15",
    studentName: "Alexander Harris",
    studentAge: 14,
    subject: "Spanish Conversation",
    duration: 55,
    status: "confirmed",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 13,
    date: "2025-07-04",
    time: "11:30",
    subject: "English Literature",
    duration: 45,
    status: "pending",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Charlotte Clark", age: 12, status: "Trial Lesson" },
      { name: "Amelia Walker", age: 13, status: "Enrolled" },
      { name: "Harper King", age: 14, status: "Enrolled" },
      { name: "Ella Robinson", age: 13, status: "Trial Lesson" },
      { name: "Emma Johnson", age: 12, status: "Enrolled" },
      { name: "Michael Scott", age: 12, status: "Enrolled" },
    ],
  },
  {
    id: 14,
    date: "2025-07-15",
    time: "15:00",
    studentName: "William Lewis",
    studentAge: 16,
    subject: "German",
    duration: 60,
    status: "completed",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 15,
    date: "2025-08-01",
    time: "10:00",
    subject: "Spanish Reading",
    duration: 50,
    status: "confirmed",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Amelia Walker", age: 13, status: "Enrolled" },
      { name: "Benjamin Lee", age: 15, status: "Enrolled" },
      { name: "Sophia Davis", age: 13, status: "Trial Lesson" },
      { name: "Charlotte Clark", age: 12, status: "Enrolled" },
      { name: "Ethan Brown", age: 16, status: "Trial Lesson" },
    ],
  },
  {
    id: 16,
    date: "2025-08-12",
    time: "09:30",
    studentName: "Daniel Young",
    studentAge: 15,
    subject: "Japanese Writing",
    duration: 60,
    status: "cancelled",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 17,
    date: "2025-09-05",
    time: "13:00",
    subject: "Spanish",
    duration: 45,
    status: "pending",
    type: "online",
    courseType: "Group",
    students: [
      { name: "Harper King", age: 14, status: "Enrolled" },
      { name: "Olivia Martinez", age: 12, status: "Trial Lesson" },
      { name: "Emma Johnson", age: 12, status: "Enrolled" },
      { name: "Benjamin Lee", age: 15, status: "Enrolled" },
      { name: "Mia White", age: 13, status: "Trial Lesson" },
    ],
  },
  {
    id: 18,
    date: "2025-09-18",
    time: "16:30",
    studentName: "Michael Scott",
    studentAge: 12,
    subject: "English Grammar",
    duration: 60,
    status: "confirmed",
    type: "in-person",
    courseType: "1-on-1",
  },
  {
    id: 19,
    date: "2025-10-10",
    time: "11:00",
    studentName: "Ella Robinson",
    studentAge: 13,
    subject: "Spanish Conversation",
    duration: 50,
    status: "completed",
    type: "online",
    courseType: "1-on-1",
  },
  {
    id: 20,
    date: "2025-10-25",
    time: "14:00",
    subject: "French",
    duration: 60,
    status: "pending",
    type: "in-person",
    courseType: "Group",
    students: [
      { name: "Henry Carter", age: 15, status: "Enrolled" },
      { name: "Liam Smith", age: 14, status: "Trial Lesson" },
      { name: "Ethan Brown", age: 16, status: "Enrolled" },
      { name: "James Anderson", age: 13, status: "Enrolled" },
      { name: "Sophia Davis", age: 13, status: "Trial Lesson" },
      { name: "Michael Scott", age: 12, status: "Enrolled" },
      { name: "Emma Johnson", age: 12, status: "Trial Lesson" },
    ],
  },
];

export default mockLessons;
