const mockLessons = [
  {
    id: "1",
    title: "Business Vocabulary and Terminology",
    description:
      "Introduction to essential business vocabulary, industry-specific terms, and professional language.",
    duration: 3,
    teacherId: "1",
    order: 1,
    status: "draft",
    objectives: "Learn 100+ business terms",
    materials: "Business dictionary, vocabulary worksheets",
    createdAt: "2025-08-10T10:00:00Z",
    isTrailAvailable: true,
  },
  {
    id: "2",
    title: "Effective Email Communication",
    description:
      "Learn how to write clear, concise, and professional business emails.",
    duration: 2,
    teacherId: "2",
    order: 2,
    status: "published",
    objectives: "Draft 5 professional emails",
    materials: "Email templates, style guide",
    createdAt: "2025-08-11T10:30:00Z",
    isTrailAvailable: false,
  },
  {
    id: "3",
    title: "Negotiation Skills",
    description:
      "Develop strategies to negotiate deals and resolve conflicts effectively.",
    duration: 4,
    teacherId: "1",
    order: 3,
    status: "draft",
    objectives: "Role-play 3 negotiation scenarios",
    materials: "Case studies, negotiation handbook",
    createdAt: "2025-08-12T11:00:00Z",
    isTrailAvailable: true,
  },
  {
    id: "4",
    title: "Presentation Skills",
    description:
      "Master techniques for engaging and persuasive business presentations.",
    duration: 3,
    teacherId: "3",
    order: 4,
    status: "published",
    objectives: "Deliver a 5-minute presentation",
    materials: "Slides, presentation checklist",
    createdAt: "2025-08-13T09:15:00Z",
    isTrailAvailable: false,
  },
  {
    id: "5",
    title: "Cross-Cultural Communication",
    description:
      "Understand cultural differences and improve international collaboration.",
    duration: 2,
    teacherId: "2",
    order: 5,
    status: "draft",
    objectives: "Analyze 3 cultural case studies",
    materials: "Culture guidebook, videos",
    createdAt: "2025-08-14T14:00:00Z",
    isTrailAvailable: true,
  },
  {
    id: "6",
    title: "Report Writing",
    description: "Learn how to structure and write formal business reports.",
    duration: 3,
    teacherId: "4",
    order: 6,
    status: "published",
    objectives: "Write a 2-page report",
    materials: "Report templates, style guide",
    createdAt: "2025-08-15T16:30:00Z",
    isTrailAvailable: true,
  },
  {
    id: "7",
    title: "Business Meetings",
    description:
      "Improve meeting etiquette, participation, and leadership skills.",
    duration: 2,
    teacherId: "1",
    order: 7,
    status: "published",
    objectives: "Simulate 2 meetings",
    materials: "Meeting agenda samples",
    createdAt: "2025-08-16T12:45:00Z",
    isTrailAvailable: true,
  },
  {
    id: "8",
    title: "Time Management",
    description: "Techniques for prioritizing tasks and boosting productivity.",
    duration: 2,
    teacherId: "3",
    order: 8,
    status: "draft",
    objectives: "Create a personal time plan",
    materials: "Time-tracking templates",
    createdAt: "2025-08-17T08:20:00Z",
    isTrailAvailable: false,
  },
  {
    id: "9",
    title: "Public Speaking Confidence",
    description: "Overcome stage fear and communicate effectively in public.",
    duration: 3,
    teacherId: "2",
    order: 9,
    status: "published",
    objectives: "Deliver a speech in class",
    materials: "Confidence-building exercises",
    createdAt: "2025-08-18T11:10:00Z",
    isTrailAvailable: false,
  },
  {
    id: "10",
    title: "Customer Service Excellence",
    description:
      "Enhance communication and problem-solving skills for customer interactions.",
    duration: 2,
    teacherId: "4",
    order: 10,
    status: "draft",
    objectives: "Handle 3 customer scenarios",
    materials: "Role-play guides, feedback forms",
    createdAt: "2025-08-19T15:25:00Z",
    isTrailAvailable: false,
  },
  {
    id: "11",
    title: "Business Writing Essentials",
    description:
      "Learn concise, persuasive writing for memos, proposals, and reports.",
    duration: 3,
    teacherId: "3",
    order: 11,
    status: "published",
    objectives: "Write 3 business documents",
    materials: "Writing handbook, sample memos",
    createdAt: "2025-08-20T09:40:00Z",
    isTrailAvailable: true,
  },
  {
    id: "12",
    title: "Leadership Skills",
    description: "Understand leadership styles and how to inspire teams.",
    duration: 4,
    teacherId: "1",
    order: 12,
    status: "draft",
    objectives: "Develop a leadership plan",
    materials: "Leadership workbook",
    createdAt: "2025-08-21T13:50:00Z",
    isTrailAvailable: false,
  },
  {
    id: "13",
    title: "Business Etiquette",
    description: "Learn professional etiquette for workplace success.",
    duration: 2,
    teacherId: "2",
    order: 13,
    status: "published",
    objectives: "Practice 5 etiquette scenarios",
    materials: "Etiquette handbook",
    createdAt: "2025-08-22T10:05:00Z",
    isTrailAvailable: false,
  },
  {
    id: "14",
    title: "Team Collaboration",
    description: "Improve teamwork and project collaboration skills.",
    duration: 3,
    teacherId: "4",
    order: 14,
    status: "draft",
    objectives: "Complete a group project",
    materials: "Collaboration tools, worksheets",
    createdAt: "2025-08-23T17:30:00Z",
    isTrailAvailable: true,
  },
  {
    id: "15",
    title: "Critical Thinking in Business",
    description:
      "Develop analytical and problem-solving skills for decision-making.",
    duration: 4,
    teacherId: "3",
    order: 15,
    status: "published",
    objectives: "Solve 3 case studies",
    materials: "Case study book",
    createdAt: "2025-08-24T12:15:00Z",
    isTrailAvailable: false,
  },
  {
    id: "16",
    title: "Networking Skills",
    description: "Learn how to build and maintain professional connections.",
    duration: 2,
    teacherId: "1",
    order: 16,
    status: "draft",
    objectives: "Build a LinkedIn profile",
    materials: "Networking guide, profile examples",
    createdAt: "2025-08-25T14:45:00Z",
    isTrailAvailable: false,
  },
];

const itemsPerPage = 10;

export { mockLessons, itemsPerPage };
