export const lessonsData = [
  // Completed Lessons
  {
    id: 1,
    title: "Japanese Writing",
    date: "2025-07-02",
    time: "09:00 AM",
    color: "purple",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 2,
    title: "Spanish Conversation",
    date: "2025-07-02",
    time: "11:00 AM",
    color: "green",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 3,
    title: "Spanish Reading",
    date: "2025-07-04",
    time: "02:00 PM",
    color: "green",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 4,
    title: "English Literature",
    date: "2025-07-07",
    time: "10:30 AM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 5,
    title: "English Literature",
    date: "2025-07-09",
    time: "04:00 PM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 6,
    title: "Japanese Writing",
    date: "2025-07-12",
    time: "09:30 AM",
    color: "purple",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 7,
    title: "Spanish Conversation",
    date: "2025-07-12",
    time: "01:00 PM",
    color: "green",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 8,
    title: "English Literature",
    date: "2025-07-15",
    time: "03:30 PM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 9,
    title: "Spanish Conversation",
    date: "2025-07-15",
    time: "05:00 PM",
    color: "green",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 10,
    title: "English Literature",
    date: "2025-07-17",
    time: "11:30 AM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 11,
    title: "English Literature",
    date: "2025-07-19",
    time: "09:00 AM",
    color: "blue",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 12,
    title: "Spanish Conversation",
    date: "2025-07-21",
    time: "02:30 PM",
    color: "green",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 13,
    title: "Japanese Writing",
    date: "2025-07-21",
    time: "04:00 PM",
    color: "purple",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 14,
    title: "English Literature",
    date: "2025-07-23",
    time: "10:00 AM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 15,
    title: "English Literature",
    date: "2025-07-25",
    time: "01:30 PM",
    color: "blue",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 16,
    title: "Spanish Conversation",
    date: "2025-07-25",
    time: "03:00 PM",
    color: "green",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 17,
    title: "English Literature",
    date: "2025-07-29",
    time: "05:30 PM",
    color: "blue",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 18,
    title: "English Literature",
    date: "2025-08-17",
    time: "11:00 AM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 19,
    title: "English Literature",
    date: "2025-08-19",
    time: "02:00 PM",
    color: "blue",
    status: "completed",
    teacherId: "1",
  },

  // Pending Lessons (Future Dates)
  {
    id: 20,
    title: "Spanish Conversation",
    date: "2025-09-16",
    time: "09:00 AM",
    color: "green",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 21,
    title: "English Literature",
    date: "2025-09-17",
    time: "11:00 AM",
    color: "blue",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 22,
    title: "Spanish Conversation",
    date: "2025-09-18",
    time: "01:30 PM",
    color: "green",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 23,
    title: "English Literature",
    date: "2025-09-19",
    time: "03:00 PM",
    color: "blue",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 24,
    title: "Japanese Writing",
    date: "2025-09-21",
    time: "10:00 AM",
    color: "purple",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 25,
    title: "English Literature",
    date: "2025-09-23",
    time: "02:00 PM",
    color: "blue",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 26,
    title: "Japanese Writing",
    date: "2025-09-23",
    time: "02:00 PM",
    color: "purple",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 27,
    title: "Spanish Reading",
    date: "2025-09-23",
    time: "04:00 PM",
    color: "green",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 28,
    title: "English Literature",
    date: "2025-10-25",
    time: "04:00 PM",
    color: "blue",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 29,
    title: "Spanish Conversation",
    date: "2025-11-25",
    time: "11:30 AM",
    color: "green",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 30,
    title: "English Literature",
    date: "2025-11-29",
    time: "01:00 PM",
    color: "blue",
    status: "pending",
    teacherId: "2",
  },

  // 🗓️ Current Month (October 2025)
  {
    id: 31,
    title: "Spanish Conversation",
    date: "2025-10-03",
    time: "09:30 AM",
    color: "green",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 32,
    title: "English Literature",
    date: "2025-10-06",
    time: "11:00 AM",
    color: "blue",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 33,
    title: "Japanese Writing",
    date: "2025-10-08",
    time: "03:00 PM",
    color: "purple",
    status: "completed",
    teacherId: "1",
  },
  {
    id: 34,
    title: "Spanish Reading",
    date: "2025-10-10",
    time: "10:00 AM",
    color: "green",
    status: "completed",
    teacherId: "2",
  },
  {
    id: 35,
    title: "English Literature",
    date: "2025-10-12",
    time: "02:30 PM",
    color: "blue",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 36,
    title: "Japanese Writing",
    date: "2025-10-14",
    time: "05:00 PM",
    color: "purple",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 37,
    title: "Spanish Conversation",
    date: "2025-10-17",
    time: "11:00 AM",
    color: "green",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 38,
    title: "English Grammar Workshop",
    date: "2025-10-18",
    time: "03:30 PM",
    color: "blue",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 39,
    title: "Japanese Writing",
    date: "2025-10-22",
    time: "09:00 AM",
    color: "purple",
    status: "pending",
    teacherId: "1",
  },
  {
    id: 40,
    title: "Spanish Reading",
    date: "2025-10-22",
    time: "01:00 PM",
    color: "green",
    status: "pending",
    teacherId: "2",
  },
  {
    id: 41,
    title: "English Conversation",
    date: "2025-10-22",
    time: "04:30 PM",
    color: "blue",
    status: "pending",
    teacherId: "1",
  },
];
