const commonBreadCrumbData = {
  add: [
    { label: "Manage Courses", path: "/teacher/manage-courses" },
    { label: "Create New Course", path: "#", current: true },
  ],
  edit: [
    { label: "Manage Courses", path: "/teacher/manage-courses" },
    { label: "Edit Course", path: "#", current: true },
  ],
};

const steps = [
  { id: 1, title: "Course Info" },
  { id: 2, title: "Lesson Info" },
];

const languageOptions = [
  { value: "afrikaans", label: "Afrikaans" },
  { value: "albanian", label: "Albanian" },
  { value: "amharic", label: "Amharic" },
  { value: "arabic", label: "Arabic" },
  { value: "armenian", label: "Armenian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "basque", label: "Basque" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bengali", label: "Bengali" },
  { value: "bosnian", label: "Bosnian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "catalan", label: "Catalan" },
  { value: "cebuano", label: "Cebuano" },
  { value: "chinese", label: "Chinese" },
  { value: "corsican", label: "Corsican" },
  { value: "croatian", label: "Croatian" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "dutch", label: "Dutch" },
  { value: "english", label: "English" },
  { value: "esperanto", label: "Esperanto" },
  { value: "estonian", label: "Estonian" },
  { value: "finnish", label: "Finnish" },
  { value: "french", label: "French" },
  { value: "frisian", label: "Frisian" },
  { value: "galician", label: "Galician" },
  { value: "georgian", label: "Georgian" },
  { value: "german", label: "German" },
  { value: "greek", label: "Greek" },
  { value: "gujarati", label: "Gujarati" },
  { value: "haitian creole", label: "Haitian Creole" },
  { value: "hausa", label: "Hausa" },
  { value: "hawaiian", label: "Hawaiian" },
  { value: "hebrew", label: "Hebrew" },
  { value: "hindi", label: "Hindi" },
  { value: "hmong", label: "Hmong" },
  { value: "hungarian", label: "Hungarian" },
  { value: "icelandic", label: "Icelandic" },
  { value: "igbo", label: "Igbo" },
  { value: "indonesian", label: "Indonesian" },
  { value: "irish", label: "Irish" },
  { value: "italian", label: "Italian" },
  { value: "japanese", label: "Japanese" },
  { value: "javanese", label: "Javanese" },
  { value: "kannada", label: "Kannada" },
  { value: "kazakh", label: "Kazakh" },
  { value: "khmer", label: "Khmer" },
  { value: "kinyarwanda", label: "Kinyarwanda" },
  { value: "korean", label: "Korean" },
  { value: "kurdish (kurmanji)", label: "Kurdish (Kurmanji)" },
  { value: "kyrgyz", label: "Kyrgyz" },
  { value: "lao", label: "Lao" },
  { value: "latin", label: "Latin" },
  { value: "latvian", label: "Latvian" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "luxembourgish", label: "Luxembourgish" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malay", label: "Malay" },
  { value: "malayalam", label: "Malayalam" },
  { value: "maltese", label: "Maltese" },
  { value: "maori", label: "Maori" },
  { value: "marathi", label: "Marathi" },
  { value: "mongolian", label: "Mongolian" },
  { value: "myanmar (burmese)", label: "Myanmar (Burmese)" },
  { value: "nepali", label: "Nepali" },
  { value: "norwegian", label: "Norwegian" },
  { value: "nyanja (chichewa)", label: "Nyanja (Chichewa)" },
  { value: "odia (oriya)", label: "Odia (Oriya)" },
  { value: "pashto", label: "Pashto" },
  { value: "persian", label: "Persian" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "punjabi", label: "Punjabi" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "samoan", label: "Samoan" },
  { value: "scots gaelic", label: "Scots Gaelic" },
  { value: "serbian", label: "Serbian" },
  { value: "sesotho", label: "Sesotho" },
  { value: "shona", label: "Shona" },
  { value: "sindhi", label: "Sindhi" },
  { value: "sinhala", label: "Sinhala" },
  { value: "slovak", label: "Slovak" },
  { value: "slovenian", label: "Slovenian" },
  { value: "somali", label: "Somali" },
  { value: "spanish", label: "Spanish" },
  { value: "sundanese", label: "Sundanese" },
  { value: "swahili", label: "Swahili" },
  { value: "swedish", label: "Swedish" },
  { value: "tagalog (filipino)", label: "Tagalog (Filipino)" },
  { value: "tajik", label: "Tajik" },
  { value: "tamil", label: "Tamil" },
  { value: "tatar", label: "Tatar" },
  { value: "telugu", label: "Telugu" },
  { value: "thai", label: "Thai" },
  { value: "turkish", label: "Turkish" },
  { value: "turkmen", label: "Turkmen" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "urdu", label: "Urdu" },
  { value: "uyghur", label: "Uyghur" },
  { value: "uzbek", label: "Uzbek" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "welsh", label: "Welsh" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yiddish", label: "Yiddish" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zulu", label: "Zulu" },
];

const lessonTypeOptions = [
  { value: "online", label: "Online" },
  { value: "in-person", label: "In-Person" },
  { value: "hybrid", label: "Hybrid" },
];

export { commonBreadCrumbData, steps, languageOptions, lessonTypeOptions };
