export const lessonsData = [
  // Completed Lessons
  { id: 1, title: 'Japanese Writing', date: '2025-07-02', color: 'purple', status: 'completed' },
  { id: 2, title: 'Spanish Conversation', date: '2025-07-02', color: 'green', status: 'completed' },
  { id: 3, title: 'Spanish Reading', date: '2025-07-04', color: 'green', status: 'completed' },
  { id: 4, title: 'English Literature', date: '2025-07-07', color: 'blue', status: 'completed' },
  { id: 5, title: 'English Literature', date: '2025-07-09', color: 'blue', status: 'completed' },
  { id: 6, title: 'Japanese Writing', date: '2025-07-12', color: 'purple', status: 'completed' },
  { id: 7, title: 'Spanish Conversation', date: '2025-07-12', color: 'green', status: 'completed' },
  { id: 8, title: 'English Literature', date: '2025-07-15', color: 'blue', status: 'completed' },
  { id: 9, title: 'Spanish Conversation', date: '2025-07-15', color: 'green', status: 'completed' },
  { id: 10, title: 'English Literature', date: '2025-07-17', color: 'blue', status: 'completed' },
  { id: 11, title: 'English Literature', date: '2025-07-19', color: 'blue', status: 'completed' },
  { id: 12, title: 'Spanish Conversation', date: '2025-07-21', color: 'green', status: 'completed' },
  { id: 13, title: 'Japanese Writing', date: '2025-07-21', color: 'purple', status: 'completed' },
  { id: 14, title: 'English Literature', date: '2025-07-23', color: 'blue', status: 'completed' },
  { id: 15, title: 'English Literature', date: '2025-07-25', color: 'blue', status: 'completed' },
  { id: 16, title: 'Spanish Conversation', date: '2025-07-25', color: 'green', status: 'completed' },
  { id: 17, title: 'English Literature', date: '2025-07-29', color: 'blue', status: 'completed' },
  { id: 18, title: 'English Literature', date: '2025-08-17', color: 'blue', status: 'completed' },
  { id: 19, title: 'English Literature', date: '2025-08-19', color: 'blue', status: 'completed' },
  
  // Pending Lessons (Future Dates)
  { id: 20, title: 'Spanish Conversation', date: '2025-09-16', color: 'green', status: 'pending' },
  { id: 21, title: 'English Literature', date: '2025-09-17', color: 'blue', status: 'pending' },
  { id: 22, title: 'Spanish Conversation', date: '2025-09-18', color: 'green', status: 'pending' },
  { id: 23, title: 'English Literature', date: '2025-09-19', color: 'blue', status: 'pending' },
  { id: 24, title: 'Japanese Writing', date: '2025-09-21', color: 'purple', status: 'pending' },
  { id: 25, title: 'English Literature', date: '2025-09-23', color: 'blue', status: 'pending' },
  { id: 26, title: 'English Literature', date: '2025-10-25', color: 'blue', status: 'pending' },
  { id: 27, title: 'Spanish Conversation', date: '2025-11-25', color: 'green', status: 'pending' },
  { id: 28, title: 'English Literature', date: '2025-11-29', color: 'blue', status: 'pending' },
];