const students = [
  {
    id: 1,
    studentName: "Priya Sharma",
    studentAge: 15,
    studentImage: "https://i.pravatar.cc/150?img=5",
    title: "Mathematics - Foundations",
    date: "2025-09-03",
    time: "11:45",
    lessons: ["algebra-basics"],
  },
  {
    id: 2,
    studentName: "Yash Agarwal",
    studentAge: 23,
    studentImage: "https://i.pravatar.cc/150?img=31",
    title: "Dance - Contemporary",
    date: "2025-09-22",
    time: "16:30",
    lessons: ["warmup-techniques"],
  },
  {
    id: 3,
    studentName: "Dev Patel",
    studentAge: 19,
    studentImage: "https://i.pravatar.cc/150?img=55",
    title: "Web Development - Intro",
    date: "2025-09-07",
    time: "18:15",
    lessons: ["html-css-basics"],
  },
  {
    id: 4,
    studentName: "Rhea Nair",
    studentAge: 12,
    studentImage: "https://i.pravatar.cc/150?img=36",
    title: "Dance - Contemporary",
    date: "2025-09-20",
    time: "17:45",
    lessons: ["floor-work"],
  },
  {
    id: 5,
    studentName: "Rohan Kapoor",
    studentAge: 14,
    studentImage: "https://i.pravatar.cc/150?img=20",
    title: "Mathematics - Foundations",
    date: "2025-09-05",
    time: "10:00",
    lessons: ["geometry-fundamentals"],
  },
  {
    id: 6,
    studentName: "Anaya Gupta",
    studentAge: 18,
    studentImage: "https://i.pravatar.cc/150?img=24",
    title: "Guitar - Level 1",
    date: "2025-09-13",
    time: "20:30",
    lessons: ["basic-chords"],
  },
  {
    id: 7,
    studentName: "Meera Iyer",
    studentAge: 15,
    studentImage: "https://i.pravatar.cc/150?img=7",
    title: "Physics - Mechanics",
    date: "2025-09-08",
    time: "09:30",
    lessons: ["newtons-laws", "work-energy", "circular-motion"],
  },
  {
    id: 8,
    studentName: "Ishita Dutta",
    studentAge: 13,
    studentImage: "https://i.pravatar.cc/150?img=22",
    title: "Mathematics - Foundations",
    date: "2025-09-10",
    time: "12:30",
    lessons: ["probability-intro"],
  },
  {
    id: 9,
    studentName: "Kabir Joshi",
    studentAge: 17,
    studentImage: "https://i.pravatar.cc/150?img=44",
    title: "Physics - Mechanics",
    date: "2025-09-06",
    time: "09:45",
    lessons: ["newtons-laws", "work-energy", "circular-motion"],
  },
  {
    id: 10,
    studentName: "Lina Roy",
    studentAge: 21,
    studentImage: "https://i.pravatar.cc/150?img=8",
    title: "Web Development - Intro",
    date: "2025-09-09",
    time: "20:45",
    lessons: ["javascript-fundamentals"],
  },
  {
    id: 11,
    studentName: "Aarav Mehta",
    studentAge: 12,
    studentImage: "https://i.pravatar.cc/150?img=12",
    title: "Mathematics - Foundations",
    date: "2025-09-12",
    time: "10:30",
    lessons: ["algebra-basics", "geometry-fundamentals", "probability-intro"],
  },
  {
    id: 12,
    studentName: "Arjun Desai",
    studentAge: 20,
    studentImage: "https://i.pravatar.cc/150?img=29",
    title: "Web Development - Intro",
    date: "2025-09-11",
    time: "19:00",
    lessons: ["responsive-design"],
  },
  {
    id: 13,
    studentName: "Sara Khan",
    studentAge: 16,
    studentImage: "https://i.pravatar.cc/150?img=33",
    title: "Physics - Mechanics",
    date: "2025-09-09",
    time: "08:30",
    lessons: ["newtons-laws", "work-energy", "circular-motion"],
  },
  {
    id: 14,
    studentName: "Siddhant Rao",
    studentAge: 20,
    studentImage: "https://i.pravatar.cc/150?img=48",
    title: "Guitar - Level 1",
    date: "2025-09-14",
    time: "21:15",
    lessons: ["strumming-patterns"],
  },
  {
    id: 15,
    studentName: "Tara Sen",
    studentAge: 13,
    studentImage: "https://i.pravatar.cc/150?img=14",
    title: "Dance - Contemporary",
    date: "2025-09-18",
    time: "16:15",
    lessons: ["performance-routine"],
  },
  {
    id: 16,
    studentName: "Nisha Verma",
    studentAge: 22,
    studentImage: "https://i.pravatar.cc/150?img=16",
    title: "Web Development - Intro",
    date: "2025-09-08",
    time: "19:30",
    lessons: [
      "html-css-basics",
      "javascript-fundamentals",
      "responsive-design",
    ],
  },
  {
    id: 17,
    studentName: "Vikram Singh",
    studentAge: 19,
    studentImage: "https://i.pravatar.cc/150?img=3",
    title: "Guitar - Level 1",
    date: "2025-09-15",
    time: "20:00",
    lessons: ["simple-songs"],
  },
  {
    id: 18,
    studentName: "Ayaan Pillai",
    studentAge: 15,
    studentImage: "https://i.pravatar.cc/150?img=41",
    title: "Dance - Contemporary",
    date: "2025-09-21",
    time: "17:15",
    lessons: ["warmup-techniques", "floor-work", "performance-routine"],
  },
];

const courseOptions = [
  { label: "All Courses", value: "all" },
  { label: "Mathematics - Foundations", value: "Mathematics - Foundations" },
  { label: "Physics - Mechanics", value: "Physics - Mechanics" },
  { label: "Web Development - Intro", value: "Web Development - Intro" },
  { label: "Guitar - Level 1", value: "Guitar - Level 1" },
  { label: "Dance - Contemporary", value: "Dance - Contemporary" },
];

const courses = [
  {
    title: "Mathematics - Foundations",
    lessons: [
      { label: "Algebra Basics", value: "algebra-basics" },
      { label: "Geometry Fundamentals", value: "geometry-fundamentals" },
      { label: "Probability Intro", value: "probability-intro" },
    ],
  },
  {
    title: "Physics - Mechanics",
    lessons: [
      { label: "Newton's Laws", value: "newtons-laws" },
      { label: "Work and Energy", value: "work-energy" },
      { label: "Circular Motion", value: "circular-motion" },
    ],
  },
  {
    title: "Web Development - Intro",
    lessons: [
      { label: "HTML & CSS Basics", value: "html-css-basics" },
      { label: "JavaScript Fundamentals", value: "javascript-fundamentals" },
      { label: "Responsive Design", value: "responsive-design" },
    ],
  },
  {
    title: "Guitar - Level 1",
    lessons: [
      { label: "Basic Chords", value: "basic-chords" },
      { label: "Strumming Patterns", value: "strumming-patterns" },
      { label: "Simple Songs", value: "simple-songs" },
    ],
  },
  {
    title: "Dance - Contemporary",
    lessons: [
      { label: "Warm-up Techniques", value: "warmup-techniques" },
      { label: "Floor Work", value: "floor-work" },
      { label: "Performance Routine", value: "performance-routine" },
    ],
  },
];

const timeOptions = [
  { value: "morning", label: "Morning (8AM - 12PM)" },
  { value: "afternoon", label: "Afternoon (12PM - 5PM)" },
  { value: "evening", label: "Evening (5PM - 8PM)" },
  { value: "weekend", label: "Weekend" },
];

export { students, courseOptions, courses, timeOptions };
